<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

		<title>Exception Handling</title>

		<link rel="stylesheet" href="css/reveal.css">
		<link rel="stylesheet" href="css/theme/league.css">

		<!-- Theme used for syntax highlighting of code -->
		<link rel="stylesheet" href="lib/css/zenburn.css">

		<!-- Printing and PDF exports -->
		<script>
			var link = document.createElement( 'link' );
			link.rel = 'stylesheet';
			link.type = 'text/css';
			link.href = window.location.search.match( /print-pdf/gi ) ? 'css/print/pdf.css' : 'css/print/paper.css';
			document.getElementsByTagName( 'head' )[0].appendChild( link );
		</script>
	</head>
	<body>
		<div class="reveal">
			<div class="slides">
				<section><!--Intro-->
					<h2>Exceptional Exception Handling</h2>
					<p class=fragment>Hi I'm Derek</p>
				</section>
				<section class="stack"><!--Bio-->
					<h2>Shameless Narcissism</h2>
					<section>
						<h2 class="fragment">I'm employed</h2>
						<p class="fragment">I work at ____________.</p><!--Cylance Inc.-->
					</section>
					<section>
						<h2>I'm got a fancy piece of paper.</h2>
						<p class="fragment">I graduated from ____________.</p><!--Colorado State University-->
					</section>
					<section>
						<h2>Three of my hobbies are:</h2>
						<ul>
							<li class="fragment">Performing ____________.</li><!--Magic-->
							<li class="fragment">Playing ____________.</li><!--Board Games-->
							<li class="fragment">Watching my favourite movies, ____________.</li><!--Star Wars-->
						</ul>
					</section>
					<section>
						<h2>Freebie</h2>
						<p class="fragment">I like trivia.</p>
					</section>
				</section>
				<section><!--Trivia 1-->
					<h2>What was the first language to introduce exception handling?</h2>
					<p class="fragment">LISP 1.5</p>
					<aside class="notes">
						<ul>
							<li>Released in 1962</li>
							<li>Used ERRSET keyword. returned NIL when there was an error.</li>
						</ul>
					</aside>
				</section>
				<section><!--Trivia 2-->
					<h2>When were the Catch/Throw keywords first used?</h2>
					<p class="fragment">1972</p>
					<aside class="notes">
						<ul>
							<li>What we now call `finally` was introduced by the New Implementation of LISP (NIL) in mid 70's.</li>
							<li>UNWIND-PROTECT</li>
						</ul>
					</aside>
				</section>
				<section><!--Trivia 3-->
					<h2>When was the first paper on Structured Exception Handling Written?</h2>
					<p class="fragment">1975</p>
					<aside class="notes">
						<p>Written by John Goodenough.</p>
					</aside>
				</section>
				<section><!--Trivia 4-->
					<h2>What are developers exceptionally bad at?</h2>
					<p class="fragment">Exception Handling</p>
				</section>
				<section><!--Prevention-->
					<h2>Prevention</h2>
					<aside class="notes">
						<p>This is all about avoiding the anti-patterns, and mistakes that lead to poorly structured code.
					</aside>
				</section>
				<section class="stack"><!--Best Practice: Don't return null-->
					<h2>Do Not Pass or Return Null Values</h2>
					<section>
						<p class="fragment">null, None, nil, undefined etc.</p>
					</section>
					<section><!--class SettlersOfCatan-->
<pre><code class="hljs lang-python">class SettlersOfCatan:
  def can_build_at(self, x, y):
    for player in self.players:
      for settlement in self.settlements:
        coords = settlement.location
        if 2 &lt; coords[0] - x or 2 &lt; coords[1] - y:
          return False
    return True

  def build_settlement(self x, y):
    if self.can_build_at(x, y):
      return Settlement(x, y)
    return None
</code></pre>
					</section>
					<section><!--__main__-->
<pre><code class="hljs lang-python">if __name__ == '__main__':
  game = SettlersOfCatan()
  self.players.append(Player())
  self.players(Player())
  # Each player builds their first settlement
  self.players[0].settlements.append(game.build_settlement(1, 2))
  self.players[1].settlements.append(game.build_settlement(2, 3))
  # Each player builds their second starting settlement
  self.players[0].settlements.append(game.build_settlement(4, 7))
  self.players[1].settlements.append(game.build_settlement(3, 3))
</code></pre>
					</section>
					<section><!--AttributeError Revealed-->
<pre><code class="hljs lang-bash">AttributeError: 'NoneType' object has no attribute 'location'</code></pre>
<pre class="fragment"><code class="hljs lang-python">
# The 2nd call to build_settlement() returns None. Since the
# result is not checked None gets added to the settlements.
self.players[1].settlements.append(game.build_settlement(2, 3))

# The subsequent call to build_settlement() raises the
# AttributeError when trying to get .location from None
def can_build_at(self, x, y):
  for player.self.players:
    for settlement in self.settlements:
      coords = settlement.location
      ...
</code></pre>
					</section>
					<section>
						<p>There is one more error though!</p>
					</section>
					<section><!--Nefarious score bug revealed-->
<pre><code class="hljs lang-python">if __name__ == '__main__':
  game = SettlersOfCatan()
  self.players.append(Player())
  self.players.append(Player())
  #build first settlements
  self.players[1].settlements.append(game.build_settlement(1, 2))
  self.players[1].settlements.append(game.build_settlement(2, 3))
  for player in self.players:
    print(player.score)
</code></pre>
					</section>
					<section><!--Class Player-->
<pre><code class="hljs lang-python">class Player:
  @property
  def score(self):
    score = 0
    if self.settlements is not None:
      score += len(self.settlements)
    if self.cities is not None:
      score += len(self.cities)
    if self.has_longest_road:
	  score += 2
    if self.has_largest_army:
      score += 2
    return score
</code></pre>
					</section>
					<section><!--How to Fix it-->
						<p>Throw/Raise an exception</p>
<pre><code class="hljs lang-python">def exceptional_build_settlement(self, x, y):
  if self.cannot_build_at(x, y):
    raise InvalidPlacementError(
      f'(${x}, ${y}) is an invlaid placement.'
    )
  return Settlement(x, y)
</code></pre>
					</section>
				</section>
				<section><!--Systemization-->
					<h2>Systemization</h2><!--Maybe use Integration instead-->
					<aside class="notes">
						<p>Exceptional is a mindset not a single act. Follow the best practives everywhere.</p>
						<p>This is about setting yourself up for success.</p>
					</aside>
				</section>
				<section class="stack"><!--Don't simply catch Exception-->
					<h2>Don't catch Exception</h2>
					<section>
						<p class="fragment">unless you are catching a more specific exception first.</p>
						<p class="fragment">Even then...reserve it for a high level general catch all.</p>
					</section>
					<section><!--Example catching only exception-->
<pre><code class="hljs lang-cs">string cmdTxt = "SELECT Count(*) as MyCnt FROM MyTable";
SqlCommand cmd = new SqlCommand(cmdTxt, new SqlConnection());
try {
  cmd.connection.Open();
  SqlDataReader reader = cmd.ExecuteReader();
  reader.read();
  return Convert.ToInt32(reader["MyCnt"]);
}
catch (Exception e) {
  ErrorHandler.sendEmailNotification(e);
}
</code></pre>
					</section>
					<section><!--Example catching better exceptions-->
<pre><code class="hljs lang-cs">string cmdTxt = "SELECT count(*) as MyCnt FROM MyTable";
SqlCommand cmd = new SqlCommand(cmdTxt, new SqlConnection());
try {
  cmd.connection.Open();
  SqlDataReader reader = cmd.ExecuteReader();
  reader.read();
  return Convert.ToInt32(reader["MyCnt"]);
} catch (InvalidOperationException sqle) {
  return -1;
} catch (FormatException fe) {
  return -1;
} catch (Exception e) {
  ErrorHandler.sendEmailNotification(e);
}
</code></pre>
						<aside class="notes">
							<p>We can do better than just sending an email when an exception occurs.</p>
							<p>Some errors we know could be resolved without code changes so return a usable but obviously incorrect value.</p>
						</aside>
					</section>
				</section>
				<section class="stack"><!--One line in the try block-->
					<h2>Only include the protected line in a try block</h2>
					<section>
							<p class="fragment">Which line threw FormatException?</p>
							<p class="fragment">Which threw InvalidOperationException?</p>
					</section>
					<section><!--Example with a single line in the try block-->
<pre><code class="hljs lang-cs">try{
  cmd.connection.Open();
} catch (InvalidOperationException ioe) {
  if (cmd.connection.State == ConnectionState.Broken) {
    cmd.connection.close();
    cmd.connection.open();
  } else {
    throw ioe;
	}
	...
}
</code></pre>
						<aside class="notes">
							<p>Now we know exactly how to handle an InvalidOperationException.</p>
							<p>If the connection is broken it can be fixed simply by closing and reopening the connection.</p>
						</aside>
					</section>
				</section>
				<section class="stack"><!--Defer clean-up-->
					<h2>Defer Clean-up for the finally block</h2>
					<section>
						<p class="fragment">Unmanaged resources should be closed regardless of a success or failure.</p>
					</section>
					<section><!--Example not using finally-->
<pre><code class="hljs lang-python">def write_config(path, content):
  try:
    config = open(path, 'wx+')
    for line in content:
      config.write(line)
      config.close()
  except FileExistsError as e:
    logger.exception('Cannot overwrite existing config file')
</code></pre>
					</section>
					<section><!--Example using finally-->
<pre><code class="hljs lang-python">def write_config(path, content):
  try:
    config = open('path', 'wx+')
    for line in content:
      config.write(line)
  except FileExistsError as e:
    logger.exception('Cannot overwrite existing config file')
  finally:
    config.close()
</code></pre>
					</section>
				</section>
				<section class="stack"><!--Use context-managers--><!--I'm debating this though cause they kinda silently swallow exceptions-->
					<h2>Use Context Managers</h2>
					<section>
						<p class=fragment>The previous example can be even cleaner</p>
					</section>
					<section><!--Example using finally-->
<pre><code class="hljs lang-python">def write_config(path, content):
  try:
    config = open('path', 'wx+')
    for line in content:
      config.write(line)
  except FileExistsError as e:
    logger.exception('Cannot overwrite existing config file')
  finally:
    config.close()
</code></pre>
					</section>
					<section>
<pre><code class="hljs lang-python">def write_config(path, content):
  with open(path, 'wx+') as config_f:
    for line in content:
      config_f.write(line);
</code></pre>
					</section>
				</section>
				<section class="stack"><!--Heckendorn's Law-->
					<h2>Heckendorn's Law</h2>
					<section>
						<p class="fragment">
							"Thou shalt provide complete error messages." <br/>- Robert Heckendorn
						</p>
					</section>
					<section><!--Example of static error message-->
<pre><code class="hljs lang-cs">class Celestial {}
class DeathStar : Celestial {}
class Moon : Celestial {}

public static bool isMoon(Celestial celestial) {
  Type type = celestial.GetType();
  if (type != typeof(Moon))
    throw new ArgumentException("That's no Moon");
  ...
  return true;
}

DeathStar deathstar = new DeathStar();
isMoon(deathstar);
</code></pre>
					</section>
					<section><!--Example of dynamic error message-->
<pre><code class="hljs lang-cs">class Celestial {}
class DeathStar : Celestial {}
class Moon : Celestial {}
		
public static bool isMoon(Celestial celestial) {
  Type type = celestial.GetType();
  if (type != typeof(Moon))
    throw new ArgumentException($"A {type} is no Moon");
    ...
    return true;
  }
		
DeathStar deathstar = new DeathStar();
isMoon(deathstar);
</code></pre>
					<aside class="notes">
						<p>Instead of, "You do not have the permission for that action" say, "You do not have write permissions for `path` directory."</p>
					</aside>
					</section>
				</section>
				<section class="stack"><!--Wrap Exceptions you are re-throwing-->
					<h2>Wrap Exceptions You re-throw/raise</h2>
					<section>
						<p class="fragment">Define Exceptions for the Callers Needs.</p>
						<aside class="notes">
							<p>This applies to working with 3rd party libraries.</p>
							<p>You should only catch exceptions you throw where they can be handled.</p>
						</aside>
					</section>
					<section><!--Example of not wrapping exception -->
<pre><code class="hljs lang-python">import sqlite3
class SettingsRepository:
  def __init__(self):
    self.connection = sqlite3.connect('example.db')

  def add(self, setting):
    cursor = self.connection.cursor()
    cursor.execute(
      f'INSERT INTO settings (key, val) VALUES (?, ?)', setting
    )
</code></pre>
					</section>
					<section><!--Example wrapping exception-->
<pre><code class="hljs lang-python">import sqlite3
class SettingRepository:
  def __init__(self):
    self.connection = sqlite3('example.db')

  def add(self, setting):
    try:
      cursor = self.connection.cursor()
      cursor.execute(
        f'INSERT INTO settings (key, val) VALUES (?,?)', setting
      )
    except IntegrityError as ie:
      raise DuplicateSettingError(
        f'{setting[0]} already exists', ie
      )
</code></pre>
					</section>
					<section><!--Setting up exception wrapping in Python-->
<pre><code class="hljs lang-python">class AppError(Exception):
  def __init__(self, message, inner):
    super(AppError, self).__init__(self, message)
    self.inner = inner

class DuplicateSettingError(AppError):
  pass
</code></pre>
				</section>
				</section>
				<section class="stack"><!--Only Log when you can handle the exception-->
					<h2>Only Log Where Exception is Consumed</h2>
					<section>
						<p class="fragment">This only works if you are providing context.</p>
						<aside class="notes">
							<ul>
								<li>Heckendorn's Law</li>
								<li>Using Context Specific Exceptions i.e. Wrap Exceptions</li>
							</ul>
						</aside>
					</section>
					<section><!--Horrible logging-->
<pre><code class="hljs lang-python">def jump(speed):
  raise BorgException(f'failed jump to warp {speed}')

def jump_to_warp(speed):
  try:
    jump(speed)
  except BorgException as be:
    logger.exception(be); raise be

if __name__ == '__main__':
  try:
    jump_to_warp(5)
  except BorgException as be:
    logger.exception(be)

</code></pre>
					</section>
					<section><!--Better Logging with Riker Maneuver-->
<pre><code class="hljs lang-python">def jump(speed):
  raise BorgException(
    f'failed jump to warp {speed}. Resistance is futile.'
  )
	
def jump_to_warp(speed):
  jump(speed)
	
if __name__ == '__main__':
  try:
    jump_to_warp(5)
  except BorgException as be:
    logger.exception(be)
    riker_maneuver() # https://youtu.be/P40LIQtEE3M
</code></pre>
					</section>
				</section>
				<section><!--Differentiation-->
					<h2>Differentiation</h2>
					<aside class="notes">
						<p>
							Setting yourself apart as being truly exceptional means the developer that depends on your code has a foundation of
							good exception handling to build from.
						</p>
					</aside>
				</section>
			</div>
		</div>

		<script src="lib/js/head.min.js"></script>
		<script src="js/reveal.js"></script>

		<script>
			// More info about config & dependencies:
			// - https://github.com/hakimel/reveal.js#configuration
			// - https://github.com/hakimel/reveal.js#dependencies
			Reveal.initialize({
				dependencies: [
					{ src: 'plugin/markdown/marked.js' },
					{ src: 'plugin/markdown/markdown.js' },
					{ src: 'plugin/notes/notes.js', async: true },
					{ src: 'plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } }
				]
			});
		</script>
	</body>
</html>
