<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

		<title>Exception Handling</title>

		<link rel="stylesheet" href="css/reveal.css">
		<link rel="stylesheet" href="css/theme/league.css">

		<!-- Theme used for syntax highlighting of code -->
		<link rel="stylesheet" href="lib/css/zenburn.css">

		<!-- Printing and PDF exports -->
		<script>
			var link = document.createElement( 'link' );
			link.rel = 'stylesheet';
			link.type = 'text/css';
			link.href = window.location.search.match( /print-pdf/gi ) ? 'css/print/pdf.css' : 'css/print/paper.css';
			document.getElementsByTagName( 'head' )[0].appendChild( link );
		</script>
	</head>
	<body>
		<div class="reveal">
			<div class="slides">
				<section><!--Intro-->
					<h2>Exceptional Exception Handling</h2>
					<p class=fragment>Hi I'm Derek</p>
				</section>
				<section class="stack"><!--Bio-->
					<h2>Shameless Narcissism</h2>
					<section>
						<h2 class="fragment">I'm employed</h2>
						<p class="fragment">I work at ____________.</p><!--Cylance Inc.-->
					</section>
					<section>
						<h2>I'm got a fancy piece of paper.</h2>
						<p class="fragment">I graduated from ____________.</p><!--Colorado State University-->
					</section>
					<section>
						<h2>Three of my hobbies are:</h2>
						<ul>
							<li class="fragment">Performing ____________.</li><!--Magic-->
							<li class="fragment">Playing ____________.</li><!--Board Games-->
							<li class="fragment">Watching my favourite movies, ____________.</li><!--Star Wars-->
						</ul>
					</section>
					<section>
						<h2>Freebie</h2>
						<p class="fragment">I like trivia.</p>
					</section>
				</section>
				<section><!--Trivia 1-->
					<h2>What was the first language to introduce exception handling?</h2>
					<p class="fragment">LISP 1.5</p>
					<aside class="notes">
						<ul>
							<li>Released in 1962</li>
							<li>Used ERRSET keyword. returned NIL when there was an error.</li>
						</ul>
					</aside>
				</section>
				<section><!--Trivia 2-->
					<h2>When were the Catch/Throw keywords first used?</h2>
					<p class="fragment">1972</p>
					<aside class="notes">
						<ul>
							<li>What we now call `finally` was introduced by the New Implementation of LISP (NIL) in mid 70's.</li>
							<li>UNWIND-PROTECT</li>
						</ul>
					</aside>
				</section>
				<section><!--Trivia 3-->
					<h2>When was the first paper on Structured Exception Handling Written?</h2>
					<p class="fragment">1975</p>
					<aside class="notes">
						<p>Written by John Goodenough.</p>
					</aside>
				</section>
				<section><!--Trivia 4-->
					<h2>What are developers exceptionally bad at?</h2>
					<p class="fragment">Exception Handling</p>
				</section>
				<section><!--Prevention-->
					<h2>Prevention</h2>
					<aside class="notes">
						<p>The best way to handle exceptions is to never cause them.</p>
					</aside>
				</section>
				<section class="stack"><!--Best Practice: Don't return or pass null-->
					<h2>Don't Pass or Return Null Values</h2>
					<section>
						<p class="fragment">null, None, nil, undefined etc.</p>
					</section>
					<section><!--class SettlersOfCatan-->
<pre><code class="hljs lang-python">class SettlersOfCatan:
  def can_build_at(self, x, y):
    for player in self.players:
      for settlement in self.settlements:
        coords = settlement.location
        if 2 &lt; coords[0] - x or 2 &lt; coords[1] - y:
          return False
    return True

  def build_settlement(self x, y):
    if self.can_build_at(x, y):
      return Settlement(x, y)
    return None
</code></pre>
						<aside class="notes">
							<ul>
								<li>Ask who has played the game.</li>
								<li>Skim code and review rules for building settlements.</li>
							</ul>
						</aside>
					</section>
					<section><!--__main__-->
<pre><code class="hljs lang-python">if __name__ == '__main__':
  game = SettlersOfCatan()
  self.players.append(Player())
  self.players(Player())
  # Each player builds their first settlement
  self.players[0].settlements.append(game.build_settlement(1, 2))
  self.players[1].settlements.append(game.build_settlement(2, 3))
  # Each player builds their second starting settlement
  self.players[0].settlements.append(game.build_settlement(4, 7))
  self.players[1].settlements.append(game.build_settlement(3, 3))
</code></pre>
						<aside class="notes">
							<p>Take a minute to try and figure out what happens in this __main__()</p>
						</aside>
					</section>
					<section><!--AttributeError Revealed-->
<pre><code class="hljs lang-bash">AttributeError: 'NoneType' object has no attribute 'location'</code></pre>
<!--Thinking about removing this code snippet-->
<pre class="fragment"><code class="hljs lang-python">
# The 2nd call to build_settlement() returns None. Since the
# result is not checked None gets added to the settlements.
self.players[1].settlements.append(game.build_settlement(2, 3))

# The subsequent call to build_settlement() raises the
# AttributeError when trying to get .location from None
def can_build_at(self, x, y):
  for player.self.players:
    for settlement in self.settlements:
      coords = settlement.location
      ...
</code></pre>
						<aside class="notes">
							<ul>
								<li>Result from 2nd game.build_settlement() is not checked for None</li>
								<li>None gets appended to the list of settlements.</li>
								<li>The next time can_build_at is called an AttributeException will get thrown</li>
							</ul>
						</aside>
					</section>
					<section>
						<p>There is one more error though!</p>
					</section>
					<section><!--Nefarious score bug revealed-->
<pre><code class="hljs lang-python">if __name__ == '__main__':
  game = SettlersOfCatan()
  self.players.append(Player())
  self.players.append(Player())
  #build first settlements
  self.players[1].settlements.append(game.build_settlement(1, 2))
  self.players[1].settlements.append(game.build_settlement(2, 3))
  for player in self.players:
    print(player.score)
</code></pre>
						<aside class="notes">
							<p>What happens when we try to calculate the players scores?</p>
						</aside>
					</section>
					<section><!--Class Player-->
<pre><code class="hljs lang-python">class Player:
  @property
  def score(self):
    score = 0
    if self.settlements is not None:
      score += len(self.settlements)
    if self.cities is not None:
      score += len(self.cities)
    if self.has_longest_road:
	  score += 2
    if self.has_largest_army:
      score += 2
    return score
</code></pre>
					<aside class="notes">
							<p>Everything should be fine since there is a not None check on both self.settlements and self.cities right?</p>
							<p>Wrong! Since there can be a none in the list of settlements a player could get an extra point from an invalid placement.</p>
						</aside>
					</section>
					<section><!--How to Fix it-->
						<p>Throw/Raise an exception</p>
<pre><code class="hljs lang-python">def exceptional_build_settlement(self, x, y):
  if self.cannot_build_at(x, y):
    raise InvalidPlacementError(
      f'(${x}, ${y}) is an invalid placement.'
    )
  return Settlement(x, y)
</code></pre>
						<aside class="notes">
							<p>Simply raising an exception removes all the None checks and prevents bugs from slipping through.</p>
						</aside>
					</section>
					<section><!--Magic reveal-->
						<h1>MAGIC!</h1>
					</section>
				</section>
				<section><!--Systemization-->
					<h2>Systemization</h2><!--Maybe use Integration instead-->
					<aside class="notes">
						<p>Exceptional is a mindset not a single act. Follow the best practives everywhere.</p>
						<p>At some point you'll have to deal with exceptions. This is how to deal with them.</p>
					</aside>
				</section>
				<section class="stack"><!--Don't simply catch Exception-->
					<h2>Don't catch Exception</h2>
					<section>
						<p class="fragment">unless you are catching a more specific exception first.</p>
					</section>
					<section><!--Example catching only exception-->
<pre><code class="hljs lang-cs">string cmdTxt = "SELECT Count(*) as MyCnt FROM MyTable";
SqlCommand cmd = new SqlCommand(cmdTxt, new SqlConnection());
try {
  cmd.connection.Open();
  SqlDataReader reader = cmd.ExecuteReader();
  reader.read();
  return Convert.ToInt32(reader["MyCnt"]);
}
catch (Exception e) {
  ErrorHandler.sendEmailNotification(e);
}
</code></pre>
						<aside class="notes">
							<ul>
								<li>Usually developers do this when they don't understand what can go wrong with their call.</li>
							</ul>
						</aside>
					</section>
					<section><!--Example catching better exceptions-->
<pre><code class="hljs lang-cs">string cmdTxt = "SELECT count(*) as MyCnt FROM MyTable";
SqlCommand cmd = new SqlCommand(cmdTxt, new SqlConnection());
try {
  cmd.connection.Open();
  SqlDataReader reader = cmd.ExecuteReader();
  reader.read();
  return Convert.ToInt32(reader["MyCnt"]);
} catch (InvalidOperationException sqle) {
  return -1;
} catch (FormatException fe) {
  return -1;
} catch (Exception e) {
  ErrorHandler.sendEmailNotification(e);
}
</code></pre>
					<aside class="notes">
							<ul>
								<li>Cleaner than using return codes with switch or if/else statements.</li>
								<li>Allows us to recover in certain instances</li>
								<li>Allows more useful reporting of the error.</li>
							</ul>
						</aside>
					</section>
				</section>
				<section class="stack"><!--One line in the try block-->
					<h2>Only include the protected line in a try block</h2>
					<section>
							<p class="fragment">Which line threw FormatException?</p>
							<p class="fragment">Which threw InvalidOperationException?</p>
							<aside class="notes">
								<p>There are still a few unanswered questions about the previous example.</p>
							</aside>
					</section>
					<section><!--Example with a single line in the try block-->
<pre><code class="hljs lang-cs">try{
  cmd.connection.Open();
} catch (InvalidOperationException ioe) {
  if (cmd.connection.State == ConnectionState.Broken) {
    cmd.connection.close();
    cmd.connection.open();
  } else {
    throw ioe;
  }
	...
}
</code></pre>
						<aside class="notes">
							<p>Knowing the Open() call raises InvalidOperationException lets us fix broken connections without stopping the user action.</p>
						</aside>
					</section>
				</section>
				<section class="stack"><!--Defer clean-up-->
					<h2>Defer Clean-up for the finally block</h2>
					<section>
						<p class="fragment">Unmanaged resources should be closed regardless of a success or failure.</p>
					</section>
					<section><!--Example not using finally-->
<pre><code class="hljs lang-python">def write_config(path, content):
  try:
    config = open(path, 'wx+')
    for line in content:
      config.write(line)
      config.close()
  except FileExistsError as e:
    logger.exception('Cannot overwrite existing config file')
</code></pre>
					</section>
					<section><!--Example using finally-->
<pre><code class="hljs lang-python">def write_config(path, content):
  try:
    config = open('path', 'wx+')
    for line in content:
      config.write(line)
  except FileExistsError as e:
    logger.exception('Cannot overwrite existing config file')
  finally:
    config.close()
</code></pre>
					</section>
				</section>
				<section class="stack"><!--Use context-managers--><!--I'm debating this though cause they kinda silently swallow exceptions-->
					<h2>Use Context Managers</h2>
					<section>
						<p class=fragment>The previous example can be even cleaner</p>
					</section>
					<section><!--Example using finally-->
<pre><code class="hljs lang-python">def write_config(path, content):
  try:
    config = open('path', 'wx+')
    for line in content:
      config.write(line)
  except FileExistsError as e:
    logger.exception('Cannot overwrite existing config file')
  finally:
    config.close()
</code></pre>
					</section>
					<section>
<pre><code class="hljs lang-python">def write_config(path, content):
  with open(path, 'wx+') as config_f:
    for line in content:
      config_f.write(line);
</code></pre>
					</section>
				</section>
				<section class="stack"><!--Heckendorn's Law-->
					<h2>Heckendorn's Law</h2>
					<section>
						<p class="fragment">
							"Thou shalt provide complete error messages." <br/>- Robert Heckendorn
						</p>
						<aside class="notes">
							<ul>
								<li>Static messages don't really say anything useful. other than a timestamp or stack trace.</li>
								<li>You can always say something more than a static error message</li>
							</ul>
						</aside>
					</section>
					<section><!--Example of static error message-->
<pre><code class="hljs lang-cs">class Celestial {}
class DeathStar : Celestial {}
class Moon : Celestial {}

public static bool isMoon(Celestial celestial) {
  Type type = celestial.GetType();
  if (type != typeof(Moon))
    throw new ArgumentException("That's no Moon");
  ...
  return true;
}

DeathStar deathstar = new DeathStar();
isMoon(deathstar);
</code></pre>
					</section>
					<section><!--Example of dynamic error message-->
<pre><code class="hljs lang-cs">class Celestial {}
class DeathStar : Celestial {}
class Moon : Celestial {}
		
public static bool isMoon(Celestial celestial) {
  Type type = celestial.GetType();
  if (type != typeof(Moon))
    throw new ArgumentException($"A {type} is no Moon");
    ...
    return true;
  }
		
DeathStar deathstar = new DeathStar();
isMoon(deathstar);
</code></pre>
					<aside class="notes">
						<p>Instead of, "You do not have the permission for that action" say, "You do not have write permissions for `path` directory."</p>
					</aside>
					</section>
				</section>
				<section class="stack"><!--Wrap Exceptions you are re-throwing-->
					<h2>Wrap Exceptions You re-throw/raise</h2>
					<section>
						<p class="fragment">Define Exceptions for the Callers Needs.</p>
						<aside class="notes">
							<p>This applies to working with 3rd party libraries.</p>
							<p>Only catch re-thrown exceptions where they can be handled.</p>
						</aside>
					</section>
					<section><!--Example of not wrapping exception -->
<pre><code class="hljs lang-python">import sqlite3
class SettingsRepository:
  def __init__(self):
    self.connection = sqlite3.connect('example.db')

  def add(self, setting):
    cursor = self.connection.cursor()
    cursor.execute(
      f'INSERT INTO settings (key, val) VALUES (?, ?)', setting
    )
</code></pre>
					<aside class="notes">
						<p>Wrapping 3rd party exceptions reduces dependency on that library.</p>
					</aside>
					</section>
					<section><!--Example wrapping exception--><!--Maybe switch this to my ApplianceNotCOnfigured code-->
<pre><code class="hljs lang-python">import sqlite3
class SettingRepository:
  def __init__(self):
    self.connection = sqlite3('example.db')

  def add(self, setting):
    try:
      cursor = self.connection.cursor()
      cursor.execute(
        f'INSERT INTO settings (key, val) VALUES (?,?)', setting
      )
    except IntegrityError as ie:
      raise DuplicateSettingError(
        f'{setting[0]} already exists', ie
      )
</code></pre>
					</section>
					<section><!--Setting up exception wrapping in Python-->
<pre><code class="hljs lang-python">class AppError(Exception):
  def __init__(self, message, inner):
    super(AppError, self).__init__(self, message)
    self.inner = inner

class DuplicateSettingError(AppError):
  pass
</code></pre>
				</section>
				</section>
				<section class="stack"><!--Only Log when you can handle the exception-->
					<h2>Only Log Where Exception is Consumed</h2>
					<section>
						<p class="fragment">This only works if you are providing context.</p>
						<aside class="notes">
							<ul>
								<li>Heckendorn's Law</li>
								<li>Using Context Specific Exceptions i.e. Wrap Exceptions</li>
							</ul>
						</aside>
					</section>
					<section><!--Horrible logging-->
<pre><code class="hljs lang-python">def jump(speed):
  raise BorgException(f'failed jump to warp {speed}')

def jump_to_warp(speed):
  try:
    jump(speed)
  except BorgException as be:
    logger.exception(be); raise be

if __name__ == '__main__':
  try:
    jump_to_warp(5)
  except BorgException as be:
    logger.exception(be)

</code></pre>
					</section>
					<section><!--Better Logging with Riker Maneuver-->
<pre><code class="hljs lang-python">def jump(speed):
  raise BorgException(
    f'failed jump to warp {speed}. Resistance is futile.'
  )
	
def jump_to_warp(speed):
  jump(speed)
	
if __name__ == '__main__':
  try:
    jump_to_warp(5)
  except BorgException as be:
    logger.exception(be)
    riker_maneuver() # https://youtu.be/P40LIQtEE3M
</code></pre>
					</section>
				</section>
				<section><!--Differentiation-->
					<h2>Differentiation</h2>
					<aside class="notes">
						<p>Set yourself apart by making it easier for developers to consume your libraries.</p>
					</aside>
				</section>
				<section><!--Don't use checked exceptions-->
						<h2>Don't Use Checked Exceptions</h2>
						<p class="fragment">Looking at you Java!</p>
						<aside class="notes">Checked exceptions sounds like a good idea until a low level module throws a new exception.</aside>
				</section>
				<section><!--Document the exceptions you throw-->
					<h2>Document the exceptions you raise/throw</h2>
					<aside class="notes">
						<ul>
							<li>It's all the benefits of checked exceptions without the drawbacks.</li>
							<li>Often times it's more interesting to know what happens when something fails rather than when it works.</li>
							<li>
								<ul>
									<li>Network Errors</li>
									<li>Disk Errors</li>
									<li>OS Errors</li>
								</ul>
							</li>
							<li>Often times lack of documentation is why developers just catch exception.</li>
						</ul>
					</aside>
				</section>
				<section><!--Being Exceptional-->
					<h2>Exceptionally dealing with libraries exceptions</h2>
					<aside class="notes">
						<p>Not talking about any one here because you are all perfect developers and will follow everything we've talked about so far 
							however when you have to deal with third party libraries that didn't attend this talk.
						</p>
					</aside>
				</section>
				<section class="stack"><!--Wrap Exceptions-->
					<h2>Wrap Exceptions</h2>
					<section>
						<p class="fragment">and throw a common exception type</p>
					</section>
					<section><!--Example catching all the exceptions-->
<pre><code class="hljs lang-cs">ACMEPort port = new ACMEPort();
try {
  port.open();
} catch (DeviceResponseException e) {
  reportPortError(e);
  logger.log("Device Response exception", e)
} catch (ATM121UnlockedException e) {
  reportPortError(e);
  logger.log("Device Response exception", e)
} catch (GMXError e) {
  reportPortError(e)
  logger.log("Device Response exception", e)
} finally {
 ..
}
</code></pre>
					</section>
					<section><!--Example raising common exception-->
<pre><code class="hljs lang-cs">public class LocalPort {
  private ACMEPort port;
  public void open() {
    try {
      this.port.open();
    } catch (DeviceResponseException e) {
      throw new PortException(e);
    } catch (ATM121UnlockedException(e)) {
      throw new PortException(e);
    } catch (GMXError e) {
      throw new PortException(e);
    }
  }
}
</code></pre>
					</section>
					<section><!--Example of calling code with common exceptions-->
<pre><code class="hljs lang-cs">LocalPort port = new LocalPort();
try {
  port.open();
} catch (PortException e) {
  reportError(e)
  logger.log(e.getMessage(), e)
}
</code></pre>
					</section>
				</section>
				<section class="stack"><!--Use Special Case Pattern-->
					<h2>Use Special Case Pattern</h2>
					<section>
            <p>or the null object pattern</p>
					</section>
					<section><!--Client code without using Special Case Object-->
<pre><code class="hljs lang-cs">public calculatePay(int employeeId) {
  Employee employee = this.employees.FindByID(employeeId);
  if (employee != null) {
    if employee.isHourly() {
      return employee.rate() * employee.hoursWorked();
    }
    return employee.rate();
  }
  return 0;
}
</code></pre>
					</section>
					<section><!--Example of client code using Special Case Pattern.-->
						<p>It's much cleaner without null checks.</p>
<pre><code class="hljs lang-cs">public calculatePay(int employeeId) {
  Employee employee = this.employees.FindById(employeeId);
  if (employee.isHourly()) {
    return employee.rate() * employee.hoursWorked();
  }
  return employe.rate();
}
</code></pre>
					</section>
					<section>
						<p>return a special case when no employee is found</p>
<pre><code class="hljs lang-cs">public EmployeeRepository {
  public Employee FindById(int id) {
    try {
      this.employees.Where(e =&gt; e.Id == id);
    } catch (EmployeeNotFoundException e) {
      return NotFoundEmployee()
    }
  }
}
</code></pre>
					</section>
					<section><!--Definition of NotFoundEmployee-->
						<p>Special Case Object</p>
<pre><code class="hljs lang-cs">public NotFoundEmployee : IEmployee {
  public bool isHourly() { return false; }
  public double rate() { return 0.0; }
  public int hoursWorked() { return 0; }
}
</code></pre>
					</section>
				</section>
			</div>
		</div>

		<script src="lib/js/head.min.js"></script>
		<script src="js/reveal.js"></script>

		<script>
			// More info about config & dependencies:
			// - https://github.com/hakimel/reveal.js#configuration
			// - https://github.com/hakimel/reveal.js#dependencies
			Reveal.initialize({
				dependencies: [
					{ src: 'plugin/markdown/marked.js' },
					{ src: 'plugin/markdown/markdown.js' },
					{ src: 'plugin/notes/notes.js', async: true },
					{ src: 'plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } }
				]
			});
		</script>
	</body>
</html>
